# Generated by Django 3.1 on 2021-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0003_auto_20210810_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='corporate_gifting_disable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('UWS', 'UWS')], max_length=30),
        ),
    ]
