# Generated by Django 3.1 on 2021-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0005_auto_20210810_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('UWS', 'UWS'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sme_text',
            name='data_vending_medium_for_1_gb',
            field=models.CharField(blank=True, choices=[('OLDSIM', 'OLDSIM'), ('NEWSIM', 'NEWSIM')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sme_text',
            name='pin2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sme_text',
            name='pin3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(blank=True, choices=[('CORPORATE GIFTING', 'CORPORATE GIFTING'), ('GIFTING', 'GIFTING'), ('SME', 'SME')], help_text='Select Plan Type SME or GIFTING or CORPORATE GIFTING', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('UWS', 'UWS'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('CORPORATE GIFTING', 'CORPORATE GIFTING'), ('GIFTING', 'GIFTING'), ('SME', 'SME')], help_text='Data plan  type only .', max_length=30),
        ),
    ]
