# Generated by Django 3.1 on 2021-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0008_auto_20210812_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme_text',
            name='new_data_vending_medium_for_random',
            field=models.CharField(blank=True, choices=[('NORMAL_SLOT', 'NORMAL_SLOT'), ('OLDSIM', 'OLDSIM'), ('NEWSIM', 'NEWSIM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('USSD', 'USSD'), ('SMEPLUG', 'SMEPLUG'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SMS', 'SMS'), ('UWS', 'UWS')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('USSD', 'USSD'), ('SMEPLUG', 'SMEPLUG'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SMS', 'SMS'), ('UWS', 'UWS')], max_length=30, null=True),
        ),
    ]
