# Generated by Django 3.1 on 2021-09-25 17:40

from django.db import migrations, models
import vtuapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0010_auto_20210918_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ident',
            field=models.CharField(default=vtuapp.models.create_id, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('UWS', 'UWS'), ('USSD', 'USSD'), ('SMEPLUG', 'SMEPLUG'), ('CG_KONNECT', 'CG_KONNECT'), ('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('UWS', 'UWS'), ('USSD', 'USSD'), ('SMEPLUG', 'SMEPLUG'), ('CG_KONNECT', 'CG_KONNECT'), ('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30, null=True),
        ),
    ]
