# Generated by Django 3.1 on 2021-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0011_auto_20210925_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('CG_KONNECT', 'CG_KONNECT'), ('USSD', 'USSD'), ('SMS', 'SMS'), ('SMEPLUG', 'SMEPLUG'), ('UWS', 'UWS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='data_vending_medium',
            field=models.CharField(choices=[('SIMHOST', 'SIMHOST'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS'), ('UWS', 'UWS'), ('MSPLUG', 'MSPLUG'), ('VTUAUTO', 'VTUAUTO'), ('VTPASS', 'VTPASS'), ('SMEIFY', 'SMEIFY'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('CG_KONNECT', 'CG_KONNECT'), ('USSD', 'USSD'), ('SMS', 'SMS'), ('SMEPLUG', 'SMEPLUG'), ('UWS', 'UWS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='vtu_vending_medium',
            field=models.CharField(choices=[('SIMHOST', 'SIMHOST'), ('SMEPLUG', 'SMEPLUG'), ('SMS', 'SMS'), ('UWS', 'UWS'), ('MSPLUG', 'MSPLUG'), ('VTUAUTO', 'VTUAUTO'), ('VTPASS', 'VTPASS'), ('SMEIFY', 'SMEIFY'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE')], max_length=30, null=True),
        ),
    ]
