# Generated by Django 3.1 on 2021-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0012_auto_20210925_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('SMS', 'SMS'), ('CG_KONNECT', 'CG_KONNECT'), ('SMEPLUG', 'SMEPLUG'), ('USSD', 'USSD'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('UWS', 'UWS')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('SMS', 'SMS'), ('CG_KONNECT', 'CG_KONNECT'), ('SMEPLUG', 'SMEPLUG'), ('USSD', 'USSD'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('UWS', 'UWS')], max_length=30, null=True),
        ),
    ]
