# Generated by Django 3.1 on 2021-09-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0016_auto_20210925_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(choices=[('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SMEPLUG', 'SMEPLUG'), ('CG_KONNECT', 'CG_KONNECT'), ('UWS', 'UWS'), ('USSD', 'USSD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='gifting_data_vending_medium',
            field=models.CharField(choices=[('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG_DEVELOPED_WEBSITE'), ('SMEPLUG', 'SMEPLUG'), ('CG_KONNECT', 'CG_KONNECT'), ('UWS', 'UWS'), ('USSD', 'USSD')], max_length=30, null=True),
        ),
    ]
