"""
Django settings for nellyproject project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
#from nelly.models import  WebsiteConfiguration
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(l$9@aoio8u#xo5@q&77m3pg2j33^!1g$m(2frz!fx550yv%0d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  False
# DEBUG =  True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'threadedcomments',
    'django_comments',
    'vtuapp',
    'crispy_forms',
     "bootstrapform",
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'notifications',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'adminrestrict',


    'django.contrib.sites',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'session_security',
    'logentry_admin',
     'django_otp',
    'django_otp.plugins.otp_totp',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,

      'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
}

LOGOUT_ON_PASSWORD_CHANGE = False
ACCOUNT_EMAIL_VERIFICATION = "optional"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'adminrestrict.middleware.AdminPagesRestrictMiddleware',
     'session_security.middleware.SessionSecurityMiddleware',
]

ROOT_URLCONF = 'nellyproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                "vtuapp.context_processors.categories_processor",
            ],
        },
    },
]

WSGI_APPLICATION = 'nellyproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
     }
 }

"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'husmoadmin$husmodb',

        'USER': 'husmoadmin',
        'PASSWORD': 'mojeed2021',
        'HOST': 'husmoadmin.mysql.pythonanywhere-services.com',

        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

}
SILENCED_SYSTEM_CHECKS = ['mysql.E001']



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/husmoadmin/nellyproject/static/'
AUTH_USER_MODEL = "vtuapp.CustomUser"
LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'profile'
LOGIN_URL= 'login'


EMAIL_FILE_PATH = os.path.join(BASE_DIR,'sent_emails')
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# EMAIL SETTING START
if DEBUG == True:
     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_HOST = 'mail.smartspeedtelecom.com'
# EMAIL_HOST_USER = 'support@smartspeedtelecom.com'
# EMAIL_HOST_PASSWORD = '@z6=ROETe;S_'
# DEFAULT_FROM_EMAIL = 'support@smartspeedtelecom.com'
# SERVER_EMAIL = 'support@smartspeedtelecom.com'
# EMAIL_PORT = 26
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_FILE_PATH = os.path.join(BASE_DIR,'sent_emails')


EMAIL_HOST = 'mail.privateemail.com'
EMAIL_HOST_USER = 'support@husmodata.com'
EMAIL_HOST_PASSWORD = 'olawale12@'
DEFAULT_FROM_EMAIL = 'support@husmodata.com'
SERVER_EMAIL = 'support@husmodata.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_FILE_PATH = os.path.join(BASE_DIR,'sent_emails')




# EMAIL SETTING END

# EMAIL SETTING START

# if DEBUG == True:
#      EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#      EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.Husmodata.com'
# EMAIL_HOST_USER = 'support@Husmodata.com'
# EMAIL_HOST_PASSWORD = '%U9o.hPhUl}^'
# DEFAULT_FROM_EMAIL = 'support@Husmodata.com'
# SERVER_EMAIL = 'support@Husmodata.com'
# EMAIL_PORT = 26
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_FILE_PATH = os.path.join(BASE_DIR,'sent_emails')
# EMAIL SETTING END

#twili +17854917497
TWILIO_ACCOUNT_SID = 'AC595310278fa79275fbce4cc73d0c795d'
TWILIO_AUTH_TOKEN= '8edad17593a6a9847474747cb92fa353'
TWILIO_DEFAULT_CALLERID ='+17854917497'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/husmoadmin/nellyproject/media/'

SITE_ID = 1
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
